package com.example.demoCulaSystem.model;

import org.springframework.stereotype.Component;

public enum Category {
    FULLSTACK, FRONTEND, BACKEND,  QA, UX, UI , AUTOMATION , SECURITY,INFRASTRUCTURE,CLOUD_SECURITY_ENGINEER, QUALITY_ASSURANCE_ENGINEER,
    WEB_DEVELOPER, ANDROID_DEVELOPER, SOLUTIONS_ENGINEER, DEVOPS_ENGINEER, FRAMEWORK_DEVELOPER, BIGDATA, MOBILE_DEVELOPER, CYBER,
    FIRMWARE_VALIDATION, DESIGN_SYSTEM, SUPPORT_ENGINEER, MARKETING_WEB_DEVELOPER


    }
